---
- name: Configura Link Secundario
  ios_config:
    lines: 
      - ip address {{ ip_add2 }} 255.255.255.255
    parents: interface loopback 70
    before: interface loopback 70
  when: link == "sec"

- name: Configura Link Primario
  ios_config:
    lines:
      - no interface loopback 70
  when: link == "pri"
