---

- name: Network LAB - AS-PATH - REGEX 
  connection: network_cli 
  gather_facts: false 
  hosts: RT_2

  tasks:
  - name: Adicionar registro as_path
    ios_config:
      lines: ip as-path access-list 10 permit _{{ item }}$
      before: no ip as-path access-list 10
    loop: "{{ regex }}"