- name: Network LAB - ANUNCIOS
  connection: network_cli 
  gather_facts: false 
  hosts: all

  tasks:
  - name: Anunciar Prefixos Nacionais com comunidades
    ios_config:
      lines: network {{ BGP_Net }} route-map {{ anuncio }} 
      parents: 
          - router bgp 100
    when: tipo == 'nacional'

  # - name: Anunciar Prefixos Nacionais com comunidades
  #   ios_config:
  #     lines: network {{ BGP_Net }} route-map {{ Rmap_nac }} 
  #     parents: 
  #         - router bgp 100
  #         - address-family ipv4
  #   when: tipo == 'internacional'

  - name: Anunciar Prefixos sem comunidades
    ios_config:
      lines: network {{ BGP_Net }}  
      parents: 
          - router bgp 100
    when: tipo == 'none'

