- name: Network LAB - ANUNCIOS
  connection: network_cli 
  gather_facts: false 
  hosts: RT_2

  tasks:
  - name: Anunciar Prefixos Nacionais
    ios_config:
      lines: network '{{ BGP_Net }}' route-map '{{ BLK-NAC }}'
      parents: 
          - router bgp 100
          - address-family ipv4
