---
Routers:
  hosts: 
    RT_1:
      ansible_host: 172.20.20.1
      ansible_user: teste 
      ansible_password: teste

    link_embratel:
      ansible_host: 172.20.20.1
      ansible_user: teste 
      ansible_password: teste
    
    RT_2:
      ansible_host: 172.10.10.1
      ansible_user: teste 
      ansible_password: teste

    link_outra:
      ansible_host: 172.10.10.1
      ansible_user: teste 
      ansible_password: teste

  vars:
    ansible_network_os: ios
    neighbor_embratel: 177.1.1.2
    neighbor_outra: 177.0.0.2