---
Routers:
  hosts: 
    RT_1:
      ansible_host: 172.20.20.1
      ansible_user: teste 
      ansible_password: teste

    link_embratel:
      ansible_host: 172.20.20.1
      ansible_user: teste 
      ansible_password: teste
      neighbor: 177.1.1.2

    link_vogel:
      ansible_host: 172.20.20.1
      ansible_user: teste 
      ansible_password: teste
      neighbor: 172.5.5.5
    
    RT_2:
      ansible_host: 172.10.10.1
      ansible_user: teste 
      ansible_password: teste

    link_outra:
      ansible_host: 172.10.10.1
      ansible_user: teste 
      ansible_password: teste
      neighbor: 177.0.0.2
      my_hostname: RT_2

  vars:
    ansible_network_os: ios
    