---

- name: Network LAB-EVE 
  connection: network_cli 
  gather_facts: false 
  hosts: lab1 
  tasks: 
     - name: CRIAR LOOPBACK 0
       ios_config:
        lines:
         - interface loopback 0

     - name: CONFIGURAR LOOPBACK 0
       ios_config:
        lines:
         - ip address {{ ip-loopback }} {{ mask }}
        parents: interface loopback 0