---

- name: Network LAB-EVE 
  connection: network_cli 
  gather_facts: false 
  hosts: lab1 
  tasks: 
     - name: CRIAR LOOPBACK 60
       ios_config:
        lines:
         - interface loopback 60
         - no shutdown

     - name: CONFIGURAR LOOPBACK 60
       ios_l3_interfaces:
         config:
          - name: loopback 60
            ipv4:
            - address: "{{ address }}"