---

- name: Network LAB-EVE 
  connection: network_cli 
  gather_facts: false 
  hosts: lab1 
  tasks: 
     - name: CRIAR LOOPBACK 0
       ios_config:
        lines:
         - interface loopback 0

     - name: CONFIGURAR LOOPBACK 0
       ios_l3_interfaces:
         config:
          - name: loopback 0
            ipv4:
            - address: "{{ address }}"