---

- name: Network LAB1-EVE - BGP ATRIBUTOS
  connection: network_cli 
  gather_facts: false 
  hosts: "{{ link }}"

  tasks:
    - name: INCLUDE ROLE
      include_role: lab1 
      apply:
        tags: 
        - atributos