---

- name: Network LAB1-EVE - BGP ATRIBUTOS
  connection: network_cli 
  gather_facts: false 
  hosts: "{{ link }}"

  tasks:
    - include_role: 
      name: lab1 
      apply:
      tags: atributos