---

- name: Configurações Gerais para Switches
  connection: network_cli 
  gather_facts: false 
  hosts: SW_LAB 
  tasks: 
    - name: Get config for IOS devices
      ios_facts: 
        gather_subset: all
  
    - name: Display the config 
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"

    - name: Autenticação Autorização e Conta
      ios_config:
        lines:
          - aaa new-model
          - aaa authentication login default group radius local
          - aaa authentication login CONSOLE local
          - aaa authentication enable default group radius enable
          - aaa authorization console
          - aaa authorization exec default group radius local
          - aaa authorization exec CONSOLE local
          - radius-server host 10.0.0.192 auth-port 1812 acct-port 1813
          - radius-server key SpeedwaykeyRadius
      tags: aaa

    - name: Novo grupo radius
      ios_config:
        lines:
          - aaa new-model
          - radius server SPWAY-SERVER
          - aaa group server radius SPWAY-RADIUS
          - aaa authentication login default group SPWAY-RADIUS local
          - aaa authentication login CONSOLE local
          - aaa authentication enable default group SPWAY-RADIUS enable
          - aaa authorization console
          - aaa authorization exec default group SPWAY-RADIUS local
          - aaa authorization exec CONSOLE local
      tags: aaa_nova

    - name: Adicionar as configurações do Radius
      ios_config:
        lines:
          - address ipv4 10.0.0.192 auth-port 1812 acct-port 1813
          - timeout 5
          - retransmit 5
          - key SpeedwaykeyRadius
        parents: radius server SPWAY-SERVER
      tags: aaa_nova

    - name: Adicionar o servidor SPWAY-SERVER no grupo SPWAY-RADIUS
      ios_config:
        lines: server name SPWAY-SERVER
        parents: aaa group server radius SPWAY-RADIUS
      tags: aaa_nova
    
    - name: Configurações Globais Padrão
      ios_config: 
        diff_against: running
        lines: 
          - service password-encryption
          - ip ssh version 2
          # - crypto key generate rsa modulus 1024
          # - ip ssh source-interface loopback 0
          - ntp server 10.0.0.192
          # - track 50 ip route {{ track_probe }} 255.255.255.252 reachability
          - hostname {{ inventory_hostname }}
      tags: padrao

    - name: Configurações do SNMP
      ios_config: 
        diff_against: running
        lines: 
          - snmp-server community speedway-snmp-ro RO
          - snmp-server location LAB-SPEEDWAY
      tags: snmp

    - name: Configurações do Logging
      ios_config: 
        diff_against: running
        lines: 
          # - logging source-interface Loopback0
          - logging 10.0.0.192
      tags: logging

    - name: Acesso remoto via terminal
      ios_config:
        lines:
          - transport input ssh
          - session-timeout 30
        parents:
          - line vty 1 4
      tags: vty

    - name: Acesso remoto via Console
      ios_config:
        lines:
          - login authentication CONSOLE
        parents:
          - line console 0
      tags: aaa_nova

