---

- name: Network Getting Started First Playbook 
  connection: network_cli 
  gather_facts: false 
  hosts: HOMELAB 
  tasks: 
    - name: Get config for IOS devices
      ios_facts: 
        gather_subset: all
  
    - name: Display the config 
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }} {{arquivo}}" 

    - name: COPY_FTP_IMAGE
      cli_command: 
        command: 'copy tftp: flash:' 
        check_all: True 
        prompt:
          - 'Address or name of remote host' 
          - 'Source filename' 
          - 'Destination filename'
        answer: 
          - "{{tftpserver}}"
          - "{{arquivo}}"
          - "{{arquivo}}"
