---

- name: Network LAB1-EVE - BGP SHUTDOWN
  connection: network_cli 
  gather_facts: false 
  hosts: "{{ link }}"
  tags: shut

  roles:
    - role: lab1

# - include_role:
#     name: lab

- name: Run tasks/hostnames.yaml instead of 'main'
  include_role:
    name: lab
    tasks_from: hostnames