---

- name: Network LAB1-EVE - BGP ATRIBUTOS
  connection: network_cli 
  gather_facts: false 
  hosts: "{{ link }}"

  tasks:
    - name: include task atributos 
      include_role:
        name: lab1 
        tasks_from: "{{ link }}"
        
  


    