---

- name: Network LAB1-EVE - BGP ATRIBUTOS
  connection: network_cli 
  gather_facts: false 
  hosts: "{{ link }}"

  tasks:
    - name: Apply tags to tasks within included file
      include_role:
        name: lab1
        apply:
          tags:
            - atributos
      tags:
        - always
        
  


    