---

- name: Configurações Gerais para Switches
  connection: network_cli 
  gather_facts: false 
  hosts: SW_LAB 
  tasks: 
    - name: Get config for IOS devices
      ios_facts: 
        gather_subset: all
  
    - name: Display the config 
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"

- name: Configurações Globais Padrão
  ios_config: 
    diff_against: running
    lines: 
      - service password-encryption
      - ip ssh version 2
      # - crypto key generate rsa modulus 1024
      # - ip ssh source-interface loopback 0
      - ntp server 10.0.0.192
      # - track 50 ip route {{ track_probe }} 255.255.255.252 reachability
      - hostname {{ inventory_hostname }}
  tags: padrao

- name: Configurações do SNMP
  ios_config: 
    diff_against: running
    lines: 
      - snmp-server community speedway-snmp-ro RO
      - snmp-server location LAB-SPEEDWAY
  tags: snmp

- name: Configurações do Logging
  ios_config: 
    diff_against: running
    lines: 
      # - logging source-interface Loopback0
      - logging 10.0.0.192
  tags: logging

- name: Acesso remoto via terminal

  ios_config:
    lines:
      - transport input ssh
    parents:
      - line vty 1 4
  tags: vty

