---

- name: Sessão BGP - Shutdown
  ios_config:
    diff_against: running
    lines: neighbor {{ link2 }} shutdown
    parents: router bgp 100
  when: bgp_shut == 'Sim'
  tags: shut

- name: Sessão BGP - NO Shutdown
  ios_config:
    diff_against: running
    lines: no neighbor {{ link2 }} shutdown
    parents: router bgp 100
  when: bgp_shut == 'Não'
  tags: shut