---

- name: Sessão BGP - Shutdown
  ios_config:
    diff_against: running
    lines: neighbor {{ link2 }} shutdown
    parents: router bgp 100
  when: bgp_shut == 'Sim'

- name: Sessão BGP - NO Shutdown
  ios_config:
    diff_against: running
    lines: neighbor {{ link2 }} no shutdown
    parents: router bgp 100
  when: bgp_shut == 'Não'